<div class="crosssell">
  <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:'); ?></h2>
  <ul id="<?php echo $this->getElementId(); ?>-container">
  </ul>
  <script type="text/javascript">decorateList('<?php echo $this->getElementId();
  ?>-container', 'none-recursive')</script>
</div>

<script id="<?php echo $this->getElementId(); ?>-template" type="text/html">
        <li class="item">
            <a class="product-image" href="/index.php/{product_url}"
            title="{name}"><img src="{thumbnail_url}" width="75" height="75"
            alt="{name}" /></a>
            <div class="product-details">
                <h3 class="product-name"><a
                href="/index.php/{product_url}">{name}</a></h3>
                {price},-
                <button type="button" title="<?php echo $this->__('Add to Cart')
                ?>" class="button btn-cart"
                onclick="setLocation('{add_to_cart_url}')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            </div>
        </li>

</script>
  <script type="text/javascript">
    jQuery(function($){
      $(document).bind('thesocialdigits.ready',function(event){
        var arguments = <?php echo $this->getApiArgumentsJson(); ?>;
        $('#<?php echo $this->getElementId();
        ?>-container').thesocialdigits('<?php echo $this->getAction(); ?>'
        , arguments
        , '#<?php echo $this->getElementId(); ?>-template', function(){
          var arguments = <?php echo $this->getCarouselArgumentsJson(); ?>;
          $('#<?php echo $this->getElementId();
          ?>-container').rcarousel(arguments);
        });
      });
    });
   </script>
