    <script type="text/javascript">
    jQuery.noConflict();
      jQuery(function($){
        $.thesocialdigits({
        key: '<?php echo $this->getApiKey() ?>',
        ga_tracking: function() {
          var trackingCategory = '<?php echo $this->getTrackingCategory() ?>';
          if(trackingCategory)
             return trackingCategory;
          return null;
        },
        datasource: function (products, callback) {
          var url = '/index.php/recommendations/list';
          var data = {
            'products': products
          };
          $.getJSON(url, data, callback);
        }
      });
      });
    </script>

  <!-- The list we want to display the popular products in. -->
  <div id="products"></div>
  
  <!-- The template to be used when rendering the products. 
       
       All variables in the template is denoted by {}, so the variable named var
       is denoted {var}. This template is applied to each product in the result
       from The Social Digits API method. Each key in the products 
       dictionary/object, given by the datasource function you have defined in
       the plugin source, is mapped to a variable name.
       
       Remember to set the type attribute to 'text/html' for templates.
   -->
  <script id="productsTemplate" type="text/html"> 
  <?php echo $this->getHtmlTemplate(); ?>
  </script>
  
  <!-- The actual use of the plugin. 
  
       This loads the three most popular products that costs less than 50 into
       the element having id 'products' using the template 'productsTemplate'.
   -->
  <script type="text/javascript">
    jQuery(function($){
      $('#products').thesocialdigits('related', 
      { 'products': [<?php echo $this->getProductId(); ?>]
      , 'limit': 3}
      , '#productsTemplate');
    
    });
   </script>
