  <!-- The list we want to display the popular products in. -->
  <div id="<?php echo $this->getElementId(); ?>"></div>
  
  <!-- The template to be used when rendering the products. 
       
       All variables in the template is denoted by {}, so the variable named var
       is denoted {var}. This template is applied to each product in the result
       from The Social Digits API method. Each key in the products 
       dictionary/object, given by the datasource function you have defined in
       the plugin source, is mapped to a variable name.
       
       Remember to set the type attribute to 'text/html' for templates.
   -->
  <script id="<?php echo $this->getHtmlTemplateId(); ?>" type="text/html"> 
  <?php echo $this->getHtmlTemplate(); ?>
  </script>
  
  <!-- The actual use of the plugin. 
  
       This loads the three most popular products that costs less than 50 into
       the element having id 'products' using the template 'productsTemplate'.
   -->
  <script type="text/javascript">
    jQuery(function($){
      $(document).bind('thesocialdigits.ready',function(event){
        var arguments = <?php echo $this->getArgumentsJson(); ?>;
        arguments.products = [<?php echo $this->getProductId(); ?>];
        $('#<?php echo $this->getElementId(); ?>').thesocialdigits('related'
        , arguments
        , '#<?php echo $this->getHtmlTemplateId(); ?>');
      });
    });
   </script>
