  <div id="<?php echo $this->getElementId(); ?>"></div>
  
  <script id="<?php echo $this->getHtmlTemplateId(); ?>" type="text/html"> 
  <?php echo $this->getHtmlTemplate(); ?>
  </script>
  
  <script type="text/javascript">
    jQuery(function($){
      $(document).bind('thesocialdigits.ready',function(event){
        var arguments = <?php echo $this->getArgumentsJson(); ?>;
        arguments.products = <?php echo $this->getProductIdJson(); ?>;
        arguments.exclude = <?php echo $this->getCartContentsJson(); ?>;
        $('#<?php echo $this->getElementId(); ?>').thesocialdigits('related'
        , arguments
        , '#<?php echo $this->getHtmlTemplateId(); ?>');
      });
    });
   </script>
