<style>
.carousel-navigation {
  display: block;
  position: absolute;
  top: 0;
  z-index: 100;
}
</style>

<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <div id="<?php echo $this->getElementId(); ?>" style="position:relative">
      <div id="<?php echo $this->getElementId(); ?>-container"
      style="margin: 0 auto;"></div>
      <?php if($this->getCarouselArgument('navigation_prev')): ?>
      <a href="#" id="<?php echo $this->getElementId(); ?>-prev" class="carousel-navigation" style="left:0;">
        <span><?php echo $this->__('Previous') ?></span>
      </a>
      <?php endif; ?>
      <?php if($this->getCarouselArgument('navigation_next')): ?>
      <a href="#" id="<?php echo $this->getElementId(); ?>-next" class="carousel-navigation" style="right:0;">
        <span><?php echo $this->__('Next'); ?></span>
      </a>
      <?php endif; ?>
    </div>
</div>

<script id="<?php echo $this->getElementId(); ?>-template" type="text/html">
  <div style="float:left; text-align:center;">
    <a href="{product_url}">
      <span><img src="{thumbnail_url}" /><br />{name}<br />{price} ,-</span>
    </a>
  </div>
</script>

<script type="text/javascript">
jQuery(function($){
  $(document).bind('thesocialdigits.ready',function(event){
    var arguments = <?php echo $this->getApiArgumentsJson(); ?>;
    $('#<?php echo $this->getElementId(); ?>-container').thesocialdigits('<?php echo $this->getAction(); ?>'
      , arguments
      , '#<?php echo $this->getElementId(); ?>-template',
      function(){
        var arguments = <?php echo $this->getCarouselArgumentsJson();?>;
        $('#<?php echo $this->getElementId(); ?>-container').rcarousel(arguments);
    });
  });
});
</script>
