<style>
.carousel-element{
  text-align:center;
}
</style>

<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <div id="<?php echo $this->getElementId(); ?>" class="rcarousel"
    width="300px;">
      <?php if($this->getCarouselArgument('navigation_prev')): ?>
      <a href="#" id="<?php echo $this->getElementId(); ?>-prev">
        <span><?php echo $this->__('Previous') ?></span>
      </a>
      <?php endif; ?>
      <div id="<?php echo $this->getElementId(); ?>-container" class="rcarousel-container"></div>
      <?php if($this->getCarouselArgument('navigation_next')): ?>
      <a href="#" id="<?php echo $this->getElementId(); ?>-next">
        <span><?php echo $this->__('Next'); ?></span>
      </a>
      <?php endif; ?>
    </div>
</div>

<script id="<?php echo $this->getElementId(); ?>-template" type="text/html">
  <div class="carousel-element">
    <a href="/index.php/{product_url}">
      <img src="{thumbnail_url}" /><br/>
        {name}<br />
        {price},-
    </a>
  </div>
</script>

<script type="text/javascript">
jQuery(function($){
  $(document).bind('thesocialdigits.ready',function(event){
    var arguments = <?php echo $this->getApiArgumentsJson(); ?>;
    $('#<?php echo $this->getElementId(); ?>-container').thesocialdigits('<?php echo $this->getAction(); ?>'
      , arguments
      , '#<?php echo $this->getElementId(); ?>-template',
      function(){
        var arguments = <?php echo $this->getCarouselArgumentsJson();?>;
        $('#<?php echo $this->getElementId(); ?>-container').rcarousel(arguments);
    });
  });
});
</script>
